# Generated by Django 3.1.4 on 2021-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('description', models.TextField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('developers', models.ManyToManyField(to='developers.Developer')),
                ('tickets', models.ManyToManyField(to='todos.Ticket')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
