# Generated by Django 3.1.4 on 2021-03-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20210314_1648'),
        ('developers', '0003_auto_20210314_1648'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='authors',
            field=models.ManyToManyField(to='authors.Author', verbose_name='tickets'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='developers',
            field=models.ManyToManyField(to='developers.Developer', verbose_name='tickets'),
        ),
    ]
