# Generated by Django 3.1.4 on 2021-03-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('grade', models.CharField(default='Unknown', max_length=32, verbose_name='Grade')),
                ('level', models.CharField(default='Junior', max_length=32, verbose_name='Level')),
            ],
        ),
    ]
