# Generated by Django 3.1.4 on 2021-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='grade',
            field=models.CharField(default='Unknown', max_length=32, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='developer',
            name='level',
            field=models.CharField(default='Junior', max_length=32, verbose_name='Level'),
        ),
    ]
